import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@shared/styles/globals.css';
import { SessionProvider } from '@app/providers/session';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: ReactNode;
  }>) {
  return (
    <html lang="en">
    <SessionProvider>
      <body className={inter.className}>{children}</body>
    </SessionProvider>
    </html>
  );
}
